import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers/client-providers";
import { auth } from './lib/auth'

import { Outfit } from "next/font/google";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
        <Providers session={session}>{children}</Providers>              
      </body>
    </html>
  );
}
